services:
  app:
    image: pcg-back
    container_name: pcg-back
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=dockerLocal
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: postgis/postgis:17-3.5-alpine
    platform: linux/amd64
    container_name: postgres-db
    environment:
      POSTGRES_DB: pcg
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    name: app-network
volumes:
  pgdata:
    name: pgdata