apiVersion: apps/v1
kind: Deployment
metadata:
  name: pcg-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pcg-app
  template:
    metadata:
      labels:
        app: pcg-app
    spec:
      containers:
        - name: pcg-app
          image: pcg-back
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dockerLocal
          imagePullPolicy: Never
          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: pcg-app-service
spec:
  selector:
    app: pcg-app
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pcg-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pcg-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
