apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pcg-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.49.240-192.168.49.250  # 이 범위는 로컬 네트워크 환경에 맞게 조정

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pcg-l2-adv
  namespace: metallb-system
spec:
  ipAddressPools:
    - pcg-pool