CREATE TABLE cards
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    customer_id       VARCHAR(255)                            NOT NULL,
    last_four_digits  VARCHAR(255)                            NOT NULL,
    is_representative BOOLEAN                                 NOT NULL,
    nickname          VARCHAR(255)                            NOT NULL,
    user_id           BIGINT,
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

CREATE TABLE cars
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    car_number VARCHAR(255)                            NOT NULL,
    user_id    BIGINT,
    CONSTRAINT pk_cars PRIMARY KEY (id)
);

CREATE TABLE email_tokens
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    token      VARCHAR(100)                            NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_email_tokens PRIMARY KEY (id)
);

CREATE TABLE parking_transactions
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    deleted_at        TIMESTAMP WITHOUT TIME ZONE,
    entry_time        TIMESTAMP WITHOUT TIME ZONE,
    exit_time         TIMESTAMP WITHOUT TIME ZONE,
    charge_start_time TIMESTAMP WITHOUT TIME ZONE,
    charge_end_time   TIMESTAMP WITHOUT TIME ZONE,
    payment_time      TIMESTAMP WITHOUT TIME ZONE,
    charge_amount     INTEGER,
    parking_amount    INTEGER,
    total_amount      INTEGER,
    user_id           BIGINT,
    park_id           BIGINT,
    car_id            BIGINT,
    car_number        VARCHAR(255),
    is_paid           BOOLEAN,
    payment_id        UUID,
    CONSTRAINT pk_parking_transactions PRIMARY KEY (id)
);

CREATE TABLE parks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status           VARCHAR(255)                            NOT NULL,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    updated_at       TIMESTAMP WITHOUT TIME ZONE,
    deleted_at       TIMESTAMP WITHOUT TIME ZONE,
    name             VARCHAR(255)                            NOT NULL,
    phone            VARCHAR(255),
    address          VARCHAR(255),
    disability_space INTEGER,
    manage_code      VARCHAR(255),
    lat              DOUBLE PRECISION,
    lon              DOUBLE PRECISION,
    ip               VARCHAR(255),
    owner_id         BIGINT,
    CONSTRAINT pk_parks PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(20),
    nickname   VARCHAR(20)                             NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    username   VARCHAR(20)                             NOT NULL,
    password   VARCHAR(200)                            NOT NULL,
    birth      date,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    roles VARCHAR(255) NOT NULL,
    PRIMARY KEY (user_id, roles),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
            REFERENCES users(id)
            ON DELETE CASCADE
);

CREATE TABLE users_cards
(
    user_id  BIGINT NOT NULL,
    cards_id BIGINT NOT NULL
);

ALTER TABLE parks
    ADD CONSTRAINT uc_parks_managecode UNIQUE (manage_code);

ALTER TABLE users_cards
    ADD CONSTRAINT uc_users_cards_cards UNIQUE (cards_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_nickname UNIQUE (nickname);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE cards
    ADD CONSTRAINT FK_CARDS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE cars
    ADD CONSTRAINT FK_CARS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE email_tokens
    ADD CONSTRAINT FK_EMAIL_TOKENS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE parking_transactions
    ADD CONSTRAINT FK_PARKING_TRANSACTIONS_ON_CAR FOREIGN KEY (car_id) REFERENCES cars (id);

ALTER TABLE parking_transactions
    ADD CONSTRAINT FK_PARKING_TRANSACTIONS_ON_PARK FOREIGN KEY (park_id) REFERENCES parks (id);

ALTER TABLE parking_transactions
    ADD CONSTRAINT FK_PARKING_TRANSACTIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE parks
    ADD CONSTRAINT FK_PARKS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE users_cards
    ADD CONSTRAINT fk_usecar_on_card FOREIGN KEY (cards_id) REFERENCES cards (id);

ALTER TABLE users_cards
    ADD CONSTRAINT fk_usecar_on_user FOREIGN KEY (user_id) REFERENCES users (id);